config/routes.rb
Rails.application.routes.draw do

  root to: 'toppages#index'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  get 'rankings/code', to: 'rankings#code'
  
  get 'signup', to: 'users#new'
  resources :users, only: [:index, :show, :new, :create] do
    member do
      get :codes
      get :followings
      get :followers
      get :favorites
    end
  end
  
  resources :posts, only: [:new, :create, :destroy] do
    member do
      get :download
    end
  end
  resources :codes, only: [:new, :create, :destroy] do
    member do
      get :download
    end
    collection do
      get :search
      get :similarity
    end
  end
  
  resources :relationships, only: [:create, :destroy]
  resources :user_posts, only: [:create, :destroy]
  resources :user_codes, only: [:create, :destroy]
  resources :comments, only: [:create, :destroy]
end

app/models/code.rb
class Code < ApplicationRecord
  belongs_to :user
  has_many :user_codes, dependent: :destroy
  
  validates :content, presence: true, length: { maximum: 511 }
  validates :summary, presence: true, length: { maximum: 50 }
  mount_uploader :data, DataUploader
  
  has_many :code_tags
  has_many :tags, through: :code_tags, source: :tag
  
  def self.search(search)
    return Code.all unless search
    Code.where(['CONCAT(summary, program, content) LIKE ?', "%#{search}%"])
  end
end

app/controllers/codes_controller.rb
class CodesController < ApplicationController
  before_action :require_user_logged_in
  before_action :correct_user, only: [:destroy]
  
  def new
    @code = current_user.codes.build
    @tags = Tag.all
  end

  def create
    @code = current_user.codes.build(code_params)
    #@tag = code.tags.build(tag_params)
    if @code.save
      flash[:success] = 'コードを公開しました。'
      redirect_to root_url
    else
      @posts = current_user.feed_posts.order('created_at DESC').page(params[:page])
      @codes = current_user.codes.order('created_at DESC').page(params[:page])
      flash[:danger] = 'コードの公開に失敗しました。'
      render 'toppages/index'
    end
  end

  def destroy
    @code.destroy
    flash[:success] = 'コードを削除しました。'
    redirect_back(fallback_location: root_path)
  end
  
  def download
    @code = Code.find(params[:id])
    filepath = @code.data.current_path
    stat = File::stat(filepath)
    send_file(filepath, :filename => @code.data_identifier, :length => stat.size)
  end
  
  def search
    @results = []
    item = Code.search(params[:keyword])
    @results = item
  end
  
  def similarity
    @program = params[:program]
    @codes = Code.all
    if @program.present?
      @similar = Cosine.calculate(@program, @codes)
      #@result = @similar.index(@similar.max)
      @results = @similar
    end
  end
  
  
  private
  
  def code_params
    params.require(:code).permit(:content, :summary, :program, :data, {tag_ids: []})
  end
  
  def correct_user
    @code = current_user.codes.find_by(id: params[:id])
    unless @code
      redirect_to root_url
    end
  end
end

app/helpers/codes_helper.rb
module CodesHelper
  require "redcarpet"
  require "coderay"
  
  REDCARPET_OPTIONS = {
    autolink: true,
    space_after_headers: true,
    no_intra_emphasis: true,
    fenced_code_blocks: true,
    tables: true,
    hard_wrap: true,
    xhtml: true,
    lax_html_blocks: true,
    strikethrough: true
  }.freeze

  def markdown_to_html(md_code)
    html_render = HTMLwithCoderay.new(filter_html: true, hard_wrap: true)
    markdown = Redcarpet::Markdown.new(html_render, REDCARPET_OPTIONS)
    markdown.render(md_code)
  end

  class HTMLwithCoderay < Redcarpet::Render::HTML
    def block_code(code, language)
      CodeRay.scan(code, :python).div
    end
  end
end

app/views/codes/_codes.html.erb
<ul class="media-list">
  <% codes.each do |code| %>
    <!-- ここでdata-targetをcode.idとしてしまうと、post.idの番号と競合して、先に出ているpostが出てきてしまう-->
    <button type="button" class="btn btn-success" data-toggle="collapse" data-target="#<%= code.summary %>">
      <p>name: <%= code.user.name %></p>
      <p>題名: <%= code.summary %></p>
      <p>公開時間: <%= code.created_at.strftime('%Y/%m/%d') %></p>
    </button>
    <div id="<%= code.summary %>" class="collapse">
      <li class="media">
        <div class="media-left">
          <img class="media-object img-rounded" src="<%= gravatar_url(code.user, { size: 50 }) %>" alt="">
        </div>
        <div>
          <div>
            <%= link_to code.user.name, user_path(code.user) %> <span class="text-muted">posted at <%= code.created_at %></span>
          </div>
          <div>
            <div class="panel panel-info">
              <div class="panel-heading">
                <h3 class="panel-title">題名</h3>
              </div>
              <div class="panel-body">
                <p><%= code.summary %></p>
              </div>
            </div>
            
            <!-- タグの表示 -->
            <div class="panel panel-success">
              <div class="panel-heading">
                <h3 class="panel-title">タグ</h3>
              </div>
              <div class="panel-body">
                <ul class="list-unstyled">
                  <% code.tags.each do |tag| %>
                    <li><%= tag.name %></li>
                  <% end %>
                </ul>
              </div>
            </div>
            <div class="panel panel-info">
              <div class="panel-heading">
                <h3 class="panel-title">プログラム</h3>
              </div>
              <div class="panel-body">
                <%= markdown_to_html(code.program).html_safe %>
              </div>
            </div>
            
            <% if code.data %>
              <p><%= link_to "データをダウンロード", download_code_path(code), class: 'btn btn-primary'%></p>
            <% end %>
            
            <div class="panel panel-default">
              <div class="panel-heading">
                <h3 class="panel-title">内容</h3>
              </div>
              <div class="panel-body">
                <div class="content">
                  <p><%= code.content %></p>
                </div>
              </div>
            </div>
          </div>
          <div>
            <%= render 'user_codes/code_favorite_button', code: code %>
            <% if current_user == code.user %>
              <%= link_to "Delete", code, method: :delete, data: { confirm: :"You sure?" }, class: 'btn btn-danger btn-xs' %>
            <% end %>
          </div>
        </div>
      </li>
    </div>
  <% end %>
  <%= paginate codes %>
</ul>

app/views/codes/new.html.erb
<div class="text-center">
  <h1>コードを公開する</h1>
</div>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%=form_for(@code) do |f| %>
      <%= render 'layouts/error_messages', model: f.object %>
      
      <div class="form-group">
        <%= f.label :program, 'プログラム' %>
        <%= f.text_area :program, class: 'form-control', placeholder: 'Markdown形式での入力(```の間にプログラムを納入する形式)', rows: 15 %>
      </div>
      
      <div class="form-group">
        <%= f.label :data, 'データ' %>
        <%= f.file_field :data %>
      </div>
      
      <div class="form-group">
        <%= f.label :tags, class: 'control-label' %>
          <div class="checkbox">
            <%= collection_check_boxes(:code, :tag_ids, Tag.all, :id, :name) do |b| %>
              <%= b.label { b.check_box + b.text } %>
            <% end %>
          </div>
      </div>
      
      <div class="form-group">
        <%= f.label :summary, '題名' %>
        <%= f.text_field :summary, class: 'form-control input-lg' %>
      </div>
      
      <div class="form-group">
        <%= f.label :content, '内容' %>
        <%= f.text_area :content, class: 'form-control',placeholder: 'プログラムの内容や添付したデータの説明などを記載してください',rows: 10 %>
      </div>
      
      <%= f.submit '公開する', class: 'btn btn-primary btn-block' %>
    <% end %>
  </div>
</div>

app/views/codes/search.html.erb
<div class="search">
  <div class="row">
    <div class="text-center">
      <%= form_tag(search_codes_path, method: :get, class: 'form-inline') do %>
        <div class="form-group">
          <%= text_field_tag :keyword, @keyword, class: 'form-control input-lg', placeholder: 'プログラム、題名、内容から検索', size: 30 %>
        </div>
        <%= submit_tag '関連ワードを検索', class: 'btn btn-primary btn-lg' %>
      <% end %>
    </div>
  </div>
</div>

<div class="text-center">
  <h2>検索されたコードの題名と公開時間を表示</h2>
</div>
<ul>
  <% @results.each do |result| %>
    <li>
      <%= link_to result.summary, codes_user_path(result.user_id) %>
      <%= result.created_at %>
    </li>
  <% end %>
</ul>

app/views/codes/similarity.html.erb
<div class="text-center">
  <h2>似たプログラムコードを探す</h2>
</div>
<div class="similarity">
  <div class="row">
    <div class="text-center">
      <%= form_tag(similarity_codes_path, method: :get, class: 'form-inline') do %>
        <div class="form-group">
          <div class="code">
            <%= text_area_tag :program, @program, class: 'form-control', placeholder: 'プログラムを入力', size: "60x20"  %>
          </div>
        </div>
        <div>
        <%= submit_tag '類似したプログラムを検索', class: 'btn btn-primary btn-lg' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

<ul>
  <% if @results.present? %>
    <% @codes.zip(@results) do |code, result| %>
    <li class="similar">
      <p><%= link_to code.user.name, codes_user_path(code.user) %></p>
      <p>題名:<%= code.summary %></p>
      <p>類似度:<%= result %></p>
    </li>
    <% end %>
  <% end %>
</ul>