config/routes.rb
Rails.application.routes.draw do

  root to: 'toppages#index'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  get 'rankings/code', to: 'rankings#code'
  
  get 'signup', to: 'users#new'
  resources :users, only: [:index, :show, :new, :create] do
    member do
      get :codes
      get :followings
      get :followers
      get :favorites
    end
  end
  
  resources :posts, only: [:new, :create, :destroy] do
    member do
      get :download
    end
  end
  resources :codes, only: [:new, :create, :destroy] do
    member do
      get :download
    end
    collection do
      get :search
      get :similarity
    end
  end
  
  resources :relationships, only: [:create, :destroy]
  resources :user_posts, only: [:create, :destroy]
  resources :user_codes, only: [:create, :destroy]
  resources :comments, only: [:create, :destroy]
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :user_posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :replies, class_name: Comment, foreign_key: :reply_comment, dependent: :destroy
  
  validates :content, presence: true, length: { maximum: 255 }
  validates :summary, presence: true, length: { maximum: 100 }
  mount_uploader :image, ImageUploader
  #serialize :image, JSON
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :require_user_logged_in
  before_action :correct_user, only: [:destroy]
  
  def new
    @post = current_user.posts.build # form_for用。次行のものだと明示していないので書き方としてやめた方がいい。
    #@post = Post.new
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      flash[:success] = '投稿に成功しました。'
      redirect_to root_url
    else
      @posts = current_user.feed_posts.order('created_at DESC').page(params[:page])
      @codes = current_user.codes.order('created_at DESC').page(params[:page])
      flash.now[:danger] = '投稿に失敗しました。'
      render 'toppages/index'
    end
  end

  def destroy
    @post.destroy
    flash[:success] = 'メッセージを削除しました。'
    redirect_back(fallback_location: root_path)
  end
  
  def download
    @post = Post.find(params[:id])
    filepath = @post.image.current_path
    stat = File::stat(filepath)
    send_file(filepath, :filename => @post.image_identifier, :length => stat.size)
  end
  
  private
  
  def post_params
    params.require(:post).permit(:content, :summary, :image)
  end
  
  def correct_user
    @post = current_user.posts.find_by(id: params[:id])
    unless @post
      redirect_to root_url
    end
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_posts.html.erb
<ul class="media-list">
  <% posts.each do |post| %>
    <button type="button" class="btn btn-success" data-toggle="collapse" data-target="#<%= post.id %>">
      <p>name: <%= post.user.name %></p>
      <p>題名: <%= post.summary %></p>
      <p>公開時間: <%= post.created_at.strftime('%Y/%m/%d') %></p>
    </button>
    
    <div id="<%= post.id %>" class="collapse">
      <li class="media">
        <div class="media-left">
          <img class="media-object img-rounded" src="<%= gravatar_url(post.user, { size: 50 }) %>" alt="">
        </div>
        <div>
          <div>
            <%= link_to post.user.name, user_path(post.user) %> <span class="text-muted">posted at <%= post.created_at %></span>
          </div>
          
          
          <div>
            <div class="panel panel-info">
              <div class="panel-heading">
                <h3 class="panel-title">題名</h3>
              </div>
              <div class="panel-body">
                <p><%= post.summary %></p>
              </div>
            </div>
            
            <% if post.image? %>
              <div class="panel panel-info">
                <div class="panel-heading">
                  <h3 class="panel-title">画像</h3>
                </div>
                <div class="panel-body">
                  <p><%= image_tag post.image.url %></p>
                  <!-- Image_uploader.rbのprocessが先に処理される大きなサイズ、version thumb:の方は小さいサムネ用の画像-->
                  <%= link_to "ダウンロード", download_post_path(post) %>
                </div>
              </div>
            <% end %>
            
            <div class="panel panel-info">
              <div class="panel-heading">
                <h3 class="panel-title">内容</h3>
              </div>
              <div class="panel-body">
                <div class="content">
                  <p><%= post.content %></p>
                </div>
              </div>
            </div>
          </div>
          
          
          <div>
            <%= render 'user_posts/favorite_button', post: post %>
            <% if current_user == post.user %>
              <%= link_to "Delete", post, method: :delete, data: { confirm: :"You sure?" }, class: 'btn btn-danger btn-xs' %>
            <% end %>
          </div>
          
          <div><h2>返信一覧</h2></div>
          <% if post.comments.present? %>
            <ul class="reply">
              <% post.comments.each_with_index do |comment, index| %>
                <li>
                  <h3>返信<%= index+1 %></h3>
                  <% if comment.parent_user_id == comment.post.id %>
                    <p>返信元: <%= link_to comment.post.user.name, user_path(comment.post.user) %></p>
                  <% end %>
                  <p>返信時間: <%= comment.created_at %></p>
                  <p>返信内容: <%= comment.content %></p>
                  <% if comment.image? %>
                    <p>添付画像: <%= image_tag comment.image.url %></p>
                  <% end %>
                  <% if current_user == comment.user %>
                    <%= link_to "Delete", comment, method: :delete, data: { confirm: :"You sure?" }, class: 'btn btn-danger btn-xs' %>
                  </li>
                  <% end %>
                <% end %>
            </ul>
          <% end %>
        </div>
        
        <%= form_for(post.comments.build) do |f| %>
          <div>
            <%= f.label :content, '内容' %>
            <%= f.text_area :content, class: 'form-control', rows: 5 %>
          </div>
          <div class="field">
            <%= f.label :image, '画像' %>
            <%= f.file_field :image %>
          </div>
          <%= hidden_field_tag :post_id, post.id %>
          <%= f.hidden_field :reply_comment, :value => post.user.name  %>
          <%= f.hidden_field :parent_user_id, :value => post.id  %>
          <%= f.submit "返信する", class: 'btn btn-info btn-xs' %>
        <% end %>
      </li>
    </div>
  <% end %>
  <%= paginate posts %>
</ul>

app/views/posts/new.html.erb
<div class="text-center">
  <h1>新規投稿する</h1>
</div>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@post) do |f| %>
      <%= render 'layouts/error_messages', model: f.object %>
      
      <div class="form-group">
        <%= f.label :summary, '題名' %>
        <%= f.text_field :summary, class: 'form-control input-lg' %>
      </div>
      
      <div class="field">
        <%= f.label :image, '画像' %>
        <%= f.file_field :image %>
      </div>
      
      <div class="form-group">
        <%= f.label :content, '内容' %>
        <%= f.text_area :content, class: 'form-control', rows: 10 %>
      </div>
      
      <%= f.submit '投稿する', class: 'btn btn-primary btn-block' %>
    <% end %>
  </div>
</div>